---
title: "Graphs"
author: "Alex"
date: "6/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(magrittr)
# Create a common graph with nodes having
# various `type` values; set to render
# always using `visNetwork` when calling
# `render_graph()`
library(DiagrammeR)
graph <-
  create_graph() %>%
  set_global_graph_attrs(
    "graph", "output", "visNetwork") %>%
  add_node("type_a", FALSE) %>%
  add_n_nodes(4, "type_b") %>%
  add_edge(1, 2) %>%
  add_edge(1, 3) %>%
  add_edge(4, 1) %>%
  add_edge(5, 1) %>%
  add_n_nodes(4, "type_c") %>%
  add_edge(1, 6) %>%
  add_edge(1, 7) %>%
  add_edge(8, 1) %>%
  add_edge(9, 1)

# View the created graph
render_graph(graph)
```

```{r}
mermaid("
graph TB
  A-->B
  A-->C
  C-->D
  B-->D
")
```

```{r}
grViz("digraph {
  graph [layout = dot, rankdir = TB]
  
  node [shape = rectangle]        
  rec1 [label = 'Step 1. Kiss my duck']
  rec2 [label = 'Step 2. Ignore my duck']
  rec3 [label =  'Step 3. GET OFF TIK TOK!']
  rec4 [label = 'Step 4. Yell at her to eat something']
  
  # edge definitions with the node IDs
  rec1 -> rec2 -> rec3 -> rec4
  }", 
  height = 500)
```


```{r}
grViz("
digraph boxes_and_circles {

  # a 'graph' statement
  graph [overlap = true, fontsize = 10]

  # several 'node' statements
  node [shape = box,
        fontname = Helvetica]
  A; B; C; D; E; F

  node [shape = circle,
        fixedsize = true,
        width = 0.9] // sets as circles
  1; 2; 3; 4; 5; 6; 7; 8

  # several 'edge' statements
  A->1 B->2 B->3 B->4 C->A
  1->D E->A 2->4 1->5 1->F
  E->6 4->6 5->7 6->7 3->8
}
")
```
